# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyAppStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyAppStore

   pod 'Alamofire','~> 4.9.0'
   pod 'AlamofireImage','~> 3.5.2'
   pod 'JGProgressHUD'

  target 'MyAppStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAppStoreUITests' do
    # Pods for testing
  end

end
